### ISSUE TITLE
Issue with resizing with xterm.js v3

### ISSUE THREAD

**Issue by amejia1** [xtermjs/xterm.js#1193]
I got an issue with resizing terminals on the new v3 release of xterm.js with the [atom-xterm](https://atom.io/packages/atom-xterm) package. When I resize, I get errors similar to the following.

```
Uncaught TypeError: Cannot read property '0' of undefined
    at TextRenderLayer.onGridChanged (C:\Users\andre\github\atom-xterm\node_modules\xterm\lib\renderer\TextRenderLayer.js:50:36)
    at C:\Users\andre\github\atom-xterm\node_modules\xterm\lib\renderer\Renderer.js:137:60
    at Array.forEach (native)
    at Renderer._refreshLoop (C:\Users\andre\github\atom-xterm\node_modules\xterm\lib\renderer\Renderer.js:137:28)
```

It also causes issue with the output from the terminal. Here's a GIF showing what I mean.

![atom-xterm-xtermjs-v3-resize-issue](https://user-images.githubusercontent.com/86134/34634718-da520c32-f254-11e7-949d-f65b7d483dac.gif)

I expect the shell line to appear at the bottom but instead it leaves me somewhere in the middle of the output from the `cat` command. There's other strange things that happen with other commands.

## Details
- Browser and browser version: Atom 1.23.1
- OS version: Windows 10
- xterm.js version: 3.0.1

### Steps to reproduce

1. `apm install amejia1/atom-xterm`
2. Open a terminal in Atom and resize it.
3. Run some commands to show issue with output from terminal.

**Comment by amejia1** [comment]
Traced this issue down to this problem https://github.com/xtermjs/xterm.js/issues/824 .
