### ISSUE TITLE
Unable to test xterm.js

### ISSUE THREAD

**Issue by dusadrian** [xtermjs/xterm.js#1362]
## Details
- Browser and browser version: Version 64.0.3282.186 (Official Build) (64-bit)
- OS version: MacOS X 10.9.5
- xterm.js version: 3.2.0

### Steps to reproduce

1. Downloaded the sources from GitHub
2. Entered the demo subdirectory
3. Opened index.html... and no terminal (all other HTML settings are there, but still no terminal)
4. Installed node.js with all necessary dependencies specified in gulpfile.js
5. Ran `npm run build`
(gulp build complains about many semantic errors such as `error TS2300: Duplicate identifier 'FontWeight'`, and finally finishes with this error:

```
TypeScript: 334 semantic errors
TypeScript: emit succeeded (with errors)
[17:12:02] Finished 'tsc' after 12 s
[17:12:02] Starting 'browserify'...
[17:12:02] Starting 'browserify-addons'...
[17:12:02] Finished 'browserify-addons' after 318 ms
[17:12:02] Starting 'sorcery-addons'...
[17:12:03] 'sorcery-addons' errored after 1.81 ms
[17:12:03] Error: ENOENT: no such file or directory, open '/Users/dusadrian/xterm.js-3.2.0/build/addons/lib/addons/attach/attach.js.map'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/Users/dusadrian/node_modules/sander/dist/sander.cjs.js:59:27)
    at getMapFromUrl (/Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:257:28)
    at getMap (/Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:301:10)
    at Node.loadSync (/Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:374:13)
    at /Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:393:10
    at Array.map (<anonymous>)
    at Node.loadSync (/Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:387:31)
    at Object.loadSync (/Users/dusadrian/node_modules/sorcery/dist/sorcery.cjs.js:713:7)
[17:12:03] Finished 'browserify' after 671 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@3.2.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@3.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
6. No idea what to do next...

**Comment by Tyriar** [comment]
@dusadrian that's weird :confused: 

>Entered the demo subdirectory
>
>Opened index.html... and no terminal (all other HTML settings are there, but still no terminal)

I'm not sure about these steps. Try this:

```
git clone https://github.com/xtermjs/xterm.js.git
cd xterm.js
npm i
npm run watch
```

Then in another terminal:

```
npm start
```

**Comment by dusadrian** [comment]
Oh, this works (thanks a lot).
Hm... could that be due to have previously installed node.js in the home directory, not in xterm.js?
Anyways, thanks again. I am beginning to build an Electron app, hopefully I will manage (newbye to all Node.js, xterm.js and Electron). Fingers crossed...
