### ISSUE TITLE
Build fails on node 10

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1891]
Related to natives poking at private APIs, need to update whichever dep uses it.

```
[css] internal/util/inspect.js:31
[css] const types = internalBinding('types');
[css]               ^
[css] 
[css] ReferenceError: internalBinding is not defined
[css]     at internal/util/inspect.js:31:15
[css]     at req_ (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:137:5)
[css]     at require (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:110:12)
[css]     at util.js:25:21
[css]     at req_ (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:137:5)
[css]     at require (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:110:12)
[css]     at fs.js:42:21
[css]     at req_ (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:137:5)
[css]     at Object.req [as require] (/home/daniel/dev/Microsoft/xterm.js/node_modules/natives/index.js:54:10)
[css]     at Object.<anonymous> (/home/daniel/dev/Microsoft/xterm.js/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
```

**Comment by Tyriar** [comment]
Definitely isn't happening anymore
