### ISSUE TITLE
Issue with npm install / fit addon gets installed close to the xterm package, not inside

### ISSUE THREAD

**Issue by franztrierweiler** [xtermjs/xterm.js#2790]
## Details
- Browser and browser version: none (nodejs issue)
- OS version: Ubuntu
- xterm.js version: 4.4.0

### Steps to reproduce

1. I have xterm@4.4.0 installed in my node_modules
2. Installing fit addon with npm install --save xterm-addon-fit does not seem to install this addon at the right location as my program keeps saying:

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/apps/nodejs_cnx/node_modules/xterm/dist/addons/fit/fit.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /home/ubuntu/apps/nodejs_cnx/server.js:17:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/apps/nodejs_cnx/server.js:16:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

only contains:

ubuntu@ip-172-26-4-202:~/apps/nodejs_cnx$ ls /home/ubuntu/apps/nodejs_cnx/node_modules/xterm/
LICENSE  README.md  css  lib  package.json  src  tsconfig.all.json  typings

fit addon is installed close to the xterm package, not inside:

ubuntu@ip-172-26-4-202:~/apps/nodejs_cnx$ ls /home/ubuntu/apps/nodejs_cnx/node_modules/
fs  xterm  xterm-addon-fit
ubuntu@ip-172-26-4-202:~/apps/nodejs_cnx$ 

Why ?

Regards

**Comment by Tyriar** [comment]
> Error: ENOENT: no such file or directory, open '/home/ubuntu/apps/nodejs_cnx/node_modules/xterm/dist/addons/fit/fit.js'

What xterm file are you linking to? Is this exception coming from some bundler?
