### ISSUE TITLE
The webgl extension fails hard when an invalid cursorStyle value is set

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3477]
Setting `cursorStyle` to `"line"` causes this exception:

```
[7072:0921/115334.522:INFO:CONSOLE(249)] "TypeError: this._cursorRenderers[n] is not a function
    at e._render (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:46909)
    at e.onGridChanged (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:46287)
    at e.renderRows (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:22525)
    at t._renderRows (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm/lib/xterm.js:1:162731)
    at e._renderCallback (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm/lib/xterm.js:1:160756)
    at e._innerRefresh (vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm/lib/xterm.js:1:36928)
    at vscode-file://vscode-app/d:/GitHub/microsoft/vscode/node_modules/xterm/lib/xterm.js:1:36644", source: vscode-file://vscode-app/d:/GitHub/microsoft/vscode/out/bootstrap-window.js (249)
```

We should handle this more gracefully, maybe by sanitizing the option at the time it's set (and Terminal.ctor). Can also check the other renderers to make sure they handle it fine, I think dom is fine,

**Comment by childrentime** [comment]
I want to take this. Any ideas to solve it? 
```typescript
constructor(options ?: ITerminalOptions) {
    const oops = options as any;
    if (oops.cursorStyle !== 'block' &&
        oops.cursorStyle !== 'underline' &&
        oops.cursorStyle !== 'bar') {
        console.warn('you have pass wrong cursorStyle property')
        oops.cursorStyle = 'block';
    }
}
export interface ITerminalOptions {
    cursorStyle?: 'block' | 'underline' | 'bar';
}
```
 I could write a function like this, but it's not elegant or extensible.
Maybe we should add default parameters to all optional parameters, and then figure out a way to extract and judge them recursively?
