### ISSUE TITLE
`npx shadow-cljs compile` fails with error, "Illegal variable reference before declaration"

### ISSUE THREAD

**Issue by dylon** [xtermjs/xterm.js#4495]
I'm trying to set up a release build for shadow-cljs that depends on xterm.js, but the Google closure compiler fails with the following message:

```
Closure compilation failed with 1 errors
--- node_modules/xterm/lib/xterm.js:2
Illegal variable reference before declaration: e
```

Since the file is minified, I tried to find an unminified version, but there does not seem to be one available.  I tried to build it from sources and received the following error during `npm install`:

```
$ npm install
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

> xterm@5.1.0 prepare
> npm run setup


> xterm@5.1.0 presetup
> node ./bin/install-addons.js

pulling addon dependencies...
/bin/sh: 1: yarn: not found
Skipped xterm-addon-attach
Skipped xterm-addon-canvas
Skipped xterm-addon-fit
Preparing xterm-addon-ligatures
npm ERR! code 2
npm ERR! path /home/dylon/Workspace/xterm.js/addons/xterm-addon-ligatures
npm ERR! command failed
npm ERR! command sh -c npm run package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dylon/.npm/_logs/2023-04-28T00_20_32_646Z-debug-0.log
node:child_process:960
    throw err;
    ^

Error: Command failed: npm install
npm ERR! code 2
npm ERR! path /home/dylon/Workspace/xterm.js/addons/xterm-addon-ligatures
npm ERR! command failed
npm ERR! command sh -c npm run package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dylon/.npm/_logs/2023-04-28T00_20_32_646Z-debug-0.log

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at /home/dylon/Workspace/xterm.js/bin/install-addons.js:49:14
    at FSReqCallback.oncomplete (node:fs:198:23) {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(696) [Uint8Array] [
       10,  62,  32, 120, 116, 101, 114, 109,  45,  97, 100, 100,
      111, 110,  45, 108, 105, 103,  97, 116, 117, 114, 101, 115,
       64,  48,  46,  54,  46,  48,  32, 112, 114, 101, 112, 117,
       98, 108, 105, 115, 104,  10,  62,  32, 110, 112, 109,  32,
      114, 117, 110,  32, 112,  97,  99, 107,  97, 103, 101,  10,
       10,  10,  62,  32, 120, 116, 101, 114, 109,  45,  97, 100,
      100, 111, 110,  45, 108, 105, 103,  97, 116, 117, 114, 101,
      115,  64,  48,  46,  54,  46,  48,  32, 112, 114, 101, 112,
       97,  99, 107,  97,
      ... 596 more items
    ],
    Buffer(280) [Uint8Array] [
      110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
      101,  32,  50,  10, 110, 112, 109,  32,  69,  82,  82,  33,
       32, 112,  97, 116, 104,  32,  47, 104, 111, 109, 101,  47,
      100, 121, 108, 111, 110,  47,  87, 111, 114, 107, 115, 112,
       97,  99, 101,  47, 120, 116, 101, 114, 109,  46, 106, 115,
       47,  97, 100, 100, 111, 110, 115,  47, 120, 116, 101, 114,
      109,  45,  97, 100, 100, 111, 110,  45, 108, 105, 103,  97,
      116, 117, 114, 101, 115,  10, 110, 112, 109,  32,  69,  82,
       82,  33,  32,  99,
      ... 180 more items
    ]
  ],
  pid: 114084,
  stdout: Buffer(696) [Uint8Array] [
     10,  62,  32, 120, 116, 101, 114, 109,  45,  97, 100, 100,
    111, 110,  45, 108, 105, 103,  97, 116, 117, 114, 101, 115,
     64,  48,  46,  54,  46,  48,  32, 112, 114, 101, 112, 117,
     98, 108, 105, 115, 104,  10,  62,  32, 110, 112, 109,  32,
    114, 117, 110,  32, 112,  97,  99, 107,  97, 103, 101,  10,
     10,  10,  62,  32, 120, 116, 101, 114, 109,  45,  97, 100,
    100, 111, 110,  45, 108, 105, 103,  97, 116, 117, 114, 101,
    115,  64,  48,  46,  54,  46,  48,  32, 112, 114, 101, 112,
     97,  99, 107,  97,
    ... 596 more items
  ],
  stderr: Buffer(280) [Uint8Array] [
    110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
    101,  32,  50,  10, 110, 112, 109,  32,  69,  82,  82,  33,
     32, 112,  97, 116, 104,  32,  47, 104, 111, 109, 101,  47,
    100, 121, 108, 111, 110,  47,  87, 111, 114, 107, 115, 112,
     97,  99, 101,  47, 120, 116, 101, 114, 109,  46, 106, 115,
     47,  97, 100, 100, 111, 110, 115,  47, 120, 116, 101, 114,
    109,  45,  97, 100, 100, 111, 110,  45, 108, 105, 103,  97,
    116, 117, 114, 101, 115,  10, 110, 112, 109,  32,  69,  82,
     82,  33,  32,  99,
    ... 180 more items
  ]
}

Node.js v18.16.0
npm ERR! code 1
npm ERR! path /home/dylon/Workspace/xterm.js
npm ERR! command failed
npm ERR! command sh -c npm run setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dylon/.npm/_logs/2023-04-28T00_19_59_069Z-debug-0.log
```

Examining the log is not much more helpful:

```
...
3050 verbose stack Error: command failed
3050 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
3050 verbose stack     at ChildProcess.emit (node:events:513:28)
3050 verbose stack     at maybeClose (node:internal/child_process:1091:16)
3050 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
3051 verbose pkgid xterm@5.1.0
3052 verbose cwd /home/dylon/Workspace/xterm.js
3053 verbose Linux 5.4.0-146-generic
3054 verbose node v18.16.0
3055 verbose npm  v9.5.1
3056 error code 1
3057 error path /home/dylon/Workspace/xterm.js
3058 error command failed
3059 error command sh -c npm run setup
3060 verbose exit 1
3061 timing npm Completed in 43284ms
3062 verbose code 1
3063 error A complete log of this run can be found in:
3063 error     /home/dylon/.npm/_logs/2023-04-28T00_19_59_069Z-debug-0.log
```

## Details
- Browser and browser version: N/A
- OS version: Ubuntu 20.04
- xterm.js version: 5.1.0

### Steps to reproduce

1. `npm install xterm`
2. Add a `require` statement to your cljs source: `(ns ... (require [xterm]))`
3. Try to build the app: `npx shadow-cljs compile ...`
4. The build will fail with the mentioned error

**Comment by jerch** [comment]
Last time I used the closure compiler it was very strict about comment annotations, and I am pretty sure xterm.js does not cover any of this. As far as I remember sources/comments need to be shaped in a certain way to work with the closure compiler.
We dont support closure compiler as a target, ofc feel free to get it compatible, but I think this is a non-trivial and exhausting endeavor.
