### ISSUE TITLE
TypeError: u.color.blend is not a function

### ISSUE THREAD

**Issue by jeanmachuca** [xtermjs/xterm.js#4567]
## Details
- Browser and browser version: Chrome is up to date
Version 114.0.5735.133 (Official Build) (x86_64)

- OS version: macOS Ventura Version 13.4
- xterm.js version: ^5.2.1

### Steps to reproduce

1. use this basic code snippet:

JS:

```javascript
/* src/test-xterm.js */
import { Terminal } from "xterm";

const baseTheme = {
    foreground: "#F8F8F8",
    background: "#2D2E2C",
    selection: "#5DA5D533",
    black: "#1E1E1D",
    brightBlack: "#262625",
    red: "#CE5C5C",
    brightRed: "#FF7272",
    green: "#5BCC5B",
    brightGreen: "#72FF72",
    yellow: "#CCCC5B",
    brightYellow: "#FFFF72",
    blue: "#5D5DD3",
    brightBlue: "#7279FF",
    magenta: "#BC5ED1",
    brightMagenta: "#E572FF",
    cyan: "#5DA5D5",
    brightCyan: "#72F0FF",
    white: "#F8F8F8",
    brightWhite: "#FFFFFF"
  };

const term = new Terminal({
    fontFamily: "\"Cascadia Code\", Menlo, monospace",
    theme: baseTheme,
    cursorBlink: true,
    allowProposedApi: true
});
const terminalElement = document.querySelector("#terminal");

// Cancel wheel events from scrolling the page if the terminal has scrollback
terminalElement?.addEventListener("wheel", e => {
    if (term.buffer.active.baseY > 0) {
        e.preventDefault();
    }
});

term.open(terminalElement);
term.write("\r\n$ ");
```

2. HTML:

```html
<!-- src/xterm.html -->
    <div id="terminal"></div>

    <script type="module">
        import "./test-xterm.js";

    </script>

```

3. Use esbuild to bundle:

```shell 
npx esbuild src/test-xterm.html src/test-xterm.js --bundle --outdir=public/ --keep-names --minify --global-name=global --sourcemap --splitting  --format=esm --target=es2021 --loader:.html=copy
```

4. Run http-server 

```shell
npx http-server
```

It is expected that it shows the xterm shell , but instead it is showing an error:

```
Uncaught TypeError: u.color.blend is not a function
    at new v (ThemeService.ts:105:40)
    at t.InstantiationService.createInstance (InstantiationService.ts:83:12)
    at H.open (Terminal.ts:470:53)
    at M.Terminal.open (Terminal.ts:143:16)
    at test-xterm.js:40:6
    at test-xterm.js:1:262
    at test-xterm.js:41:20
v @ ThemeService.ts:105
createInstance @ InstantiationService.ts:83
open @ Terminal.ts:470
open @ Terminal.ts:143
(anonymous) @ test-xterm.js:40
(anonymous) @ test-xterm.js:1
(anonymous) @ test-xterm.js:41

```

**Comment by jerch** [comment]
What is `u` at that time? Can you step debug that and show its type/value right before the exception?

**Comment by Tyriar** [comment]
I suspect esbuild is breaking xterm.js here as color is a namespace import:

https://github.com/Tyriar/xterm.js/blob/4d501b38b88ea5c4d0e1641ba3cebc5dbc629ac4/src/browser/services/ThemeService.ts#L9

**Comment by jerch** [comment]
Yeah, esbuild not mangling namespace imports correctly would also be my guess here.
