### ISSUE TITLE
Error in playwright tests: Error [TypeError]: Cannot read properties of undefined (reading 'dimensions')

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4771]
When run in CI/locally:

```
[chromium] Error [TypeError]: Cannot read properties of undefined (reading 'dimensions')
    at get dimensions [as dimensions] (http://localhost:3000/dist/client-bundle.js:30662:52)
    at Viewport._innerRefresh (http://localhost:3000/dist/client-bundle.js:26282:58)
    at http://localhost:3000/dist/client-bundle.js:26277:108
```

**Comment by Tyriar** [comment]
Same as https://github.com/xtermjs/xterm.js/issues/4775, just a different browser error format.
