### ISSUE TITLE
Error in playwright tests: Error [TypeError]: this._renderer.value is undefined

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4775]
```
[firefox] Error [TypeError]: this._renderer.value is undefined
    at get dimensions (http://localhost:3000/dist/client-bundle.js:30668:24)
    at _innerRefresh (http://localhost:3000/dist/client-bundle.js:26282:13)
    at ./out/browser/Viewport.js/_refresh/this._refreshAnimationFrame< (http://localhost:3000/dist/client-bundle.js:26277:108)
    at FrameRequestCallback*_refresh (http://localhost:3000/dist/client-bundle.js:26277:75)
    at syncScrollArea (http://localhost:3000/dist/client-bundle.js:26301:18)
    at ./out/browser/Viewport.js/reset/< (http://localhost:3000/dist/client-bundle.js:26266:74)
    at FrameRequestCallback*reset (http://localhost:3000/dist/client-bundle.js:26266:41)
    at clear (http://localhost:3000/dist/client-bundle.js:26064:70)
    at clear (http://localhost:3000/dist/client-bundle.js:27470:20)
    at  (debugger eval code line 201 > eval:1:13)
    at evaluate (debugger eval code:201:30)
    at  (debugger eval code:1:44)
    at evaluateFunction (chrome://juggler/content/content/Runtime.js:405:60)
    at callFunction (chrome://juggler/content/content/Runtime.js:104:41)
    at _onMessageInternal (chrome://juggler/content/SimpleChannel.js:237:37)
    at _onMessage (chrome://juggler/content/SimpleChannel.js:194:12)
    at bindToActor/actor.receiveMessage (chrome://juggler/content/SimpleChannel.js:39:44)
  ✓  887 [Firefox Stable] › ..\..\test\playwright\Terminal.test.ts:602:9 › API Integration Tests › modes › defaults (56ms)
```

**Comment by angadn** [comment]
@Tyriar I'm seeing a very similar issue in `5.3.0` as well as the latest beta in `5.4.0`. 
<img width="665" alt="image" src="https://github.com/xtermjs/xterm.js/assets/5404858/46619c41-76a3-42fd-92eb-0d513ff5a153">

Am I doing something wrong, is this known, or should I file a new issue?

**Comment by Tyriar** [comment]
@angadn not sure, but you should move over to the `@xterm/xterm` package

**Comment by angadn** [comment]
Thanks for pointing that out. I moved over to the `@xterm/xterm` package, but still run into the same error. Should I file a new issue?

**Comment by Tyriar** [comment]
@angadn sure
