### ISSUE TITLE
[WIN] unable to install at GULP:  "npm ERR! code ELIFECYCLE"

### ISSUE THREAD

**Issue by seanvree** [xtermjs/xterm.js#872]
Unable to install Xterm.JS.  Fails at Gulp.  NPM, NODE, and NODE-GYP are all installed:

```
c:\xterm>node-gyp -v
v3.6.2

c:\xterm>node -v
v6.11.1

c:\xterm>npm -v
5.3.0
```

## Details
- Browser and browser version: Chrome
- OS version:  Windows 10E 1703 X64
- xterm.js version: Latest 

### Steps to reproduce

1. Clone Repo
2. NPM Install

Install log:

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\

c:\>git clone https://github.com/sourcelair/xterm.js
Cloning into 'xterm.js'...
remote: Counting objects: 6360, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 6360 (delta 65), reused 83 (delta 35), pack-reused 6228
Receiving objects: 100% (6360/6360), 3.03 MiB | 1.68 MiB/s, done.
Resolving deltas: 100% (3944/3944), done.

c:\>cd xterm

c:\xterm>node-gyp -v
v3.6.2

c:\xterm>node -v
v6.11.1

c:\xterm>npm -v
5.3.0

c:\xterm>npm install

> node-pty@0.4.1 install c:\xterm\node_modules\node-pty
> node scripts/install.js


c:\xterm\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Agent.cc
  ConsoleFont.cc
  ConsoleInput.cc
  ConsoleLine.cc
  Coord.cc
  EventLoop.cc
  LargeConsoleRead.cc
  NamedPipe.cc
..\..\..\deps\winpty\agent\LargeConsoleRead.cc(35): warning C4996: 'GetVersionExW': was declared deprecated [c:\xterm\node_modules\node-pty\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(442): note: see declaration of 'GetVersionExW'
  SmallRect.cc
  Terminal.cc
  Win32Console.cc
  main.cc
  DebugClient.cc
  WinptyAssert.cc
  WinptyVersion.cc
  winpty_wcsnlen.cc
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  winpty-agent.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\\winpty-agent.exe
  winpty-agent.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\winpty-agent.pdb (Full PDB)
  winpty.cc
  DebugClient.cc
  win_delay_load_hook.cc
     Creating library c:\xterm\node_modules\node-pty\build\Release\winpty.lib and object c:\xterm\node_modules\node-pty\build\Release\winpty.exp
  Generating code
  Finished generating code
  winpty.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\\winpty.dll
  winpty.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\winpty.pdb (Full PDB)
  pty.cc
  win_delay_load_hook.cc
c:\xterm\node_modules\node-pty\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\src\win\pty.cc) [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
  c:\users\administrator\.node-gyp\6.11.1\include\node\v8.h(3033): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\win\pty.cc)
c:\xterm\node_modules\node-pty\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source file ..\src\win\pty.cc) [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
  c:\users\administrator\.node-gyp\6.11.1\include\node\v8.h(4009): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\win\pty.cc)
c:\xterm\node_modules\node-pty\node_modules\nan\nan.h(1955): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\win\pty.cc) [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
  c:\users\administrator\.node-gyp\6.11.1\include\node\v8.h(2756): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\win\pty.cc)
..\src\win\pty.cc(67): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(67): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(78): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(78): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(210): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(210): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [c:\xterm\node_modules\node-pty\build\pty.vcxproj]
     Creating library c:\xterm\node_modules\node-pty\build\Release\pty.lib and object c:\xterm\node_modules\node-pty\build\Release\pty.exp
  Generating code
  Finished generating code
  pty.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\\pty.node
  pty.vcxproj -> c:\xterm\node_modules\node-pty\build\Release\pty.pdb (Full PDB)


> node-pty@0.4.1 postinstall c:\xterm\node_modules\node-pty
> node scripts/post-install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> xterm@2.9.1 prepublish c:\xterm
> npm run build


> xterm@2.9.1 build c:\xterm
> gulp build

[06:07:09] Using gulpfile c:\xterm\gulpfile.js
[06:07:09] Starting 'tsc'...
[06:07:09] 'tsc' errored after 653 μs
[06:07:09] Error: c:\xterm/c:/xterm/lib contains invalid WIN32 path characters.
    at Object.mkdirsSync (c:\xterm\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:16:20)
    at Object.emptyDirSync (c:\xterm\node_modules\fs-extra\lib\empty\index.js:33:18)
    at Gulp.<anonymous> (c:\xterm\gulpfile.js:37:6)
    at module.exports (c:\xterm\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\xterm\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\xterm\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (c:\xterm\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at c:\xterm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:51:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@2.9.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.9.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-08-08T13_07_09_098Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@2.9.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.9.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-08-08T13_07_09_223Z-debug.log

c:\xterm>
```

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
