### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [xtermjs/xterm.js#954]
#  uname -a
Linux xxb001 2.6.39-200.24.1.el6uek.x86_64 #1 SMP Sat Jun 23 02:39:07 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

# node -v
v8.4.0

/usr/mtx/xterm.js

```
# cat /etc/issue
Oracle Linux Server release 6.3
Kernel \r on an \m
```

```
# npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle xterm@2.9.1~prepublish: cannot run in wd %s %s (wd=%s) xterm@2.9.1 npm run build /usr/mtx/xterm.js
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.
npm WARN request-promise-native@1.0.4 requires a peer of request@^2.34 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 115 packages and updated 92 packages in 191.841s
[root@xxb001 xterm.js]# npm start

> xterm@2.9.1 prestart /usr/mtx/xterm.js
> npm run build


> xterm@2.9.1 build /usr/mtx/xterm.js
> gulp build

[10:26:38] Using gulpfile /usr/mtx/xterm.js/gulpfile.js
[10:26:38] Starting 'tsc'...
[10:26:42] Finished 'tsc' after 4.65 s
[10:26:42] Starting 'browserify'...
[10:26:42] Starting 'browserify-addons'...
[10:26:43] Finished 'browserify-addons' after 429 ms
[10:26:43] Starting 'sorcery-addons'...
[10:26:43] Finished 'sorcery-addons' after 6.2 ms
[10:26:43] Finished 'browserify' after 458 ms
[10:26:43] Starting 'sorcery'...
[10:26:43] Finished 'sorcery' after 93 ms
[10:26:43] Starting 'build'...
[10:26:43] Finished 'build' after 68 Œºs

> xterm@2.9.1 start /usr/mtx/xterm.js
> node demo/app

Cannot find module '../build/Release/pty.node'
module.js:491
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m57.node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/mtx/xterm.js/node_modules/node-pty/lib/pty.js:18:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@2.9.1 start: `node demo/app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@2.9.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-08T02_26_43_915Z-debug.log

```

**Comment by parisk** [comment]
Hi @hktalent. Do you have a C++ compiler on your system (gcc or clang)?

If not, can you please try installing one and then retry?

If yes, can you please locate `pty.js` in your system (it should be in `/usr/mtx/xterm.js/node_modules/pty.js`), run `make` in that directory and then give it another try?

**Comment by Tyriar** [comment]
We changed it recently, it should be `/usr/mtx/xterm.js/node_modules/node-pty`. I haven't tested on node 8 yet but I'm expecting failure messages in `npm install` related to `node-pty`?

**Comment by hktalent** [comment]
@Tyriar @parisk 

```
# gcc  -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
```
```

# proxychains4 yum install node-pty
[proxychains] config file found: /usr/local//etc/proxychains.conf
[proxychains] preloading /usr/local//lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
Loaded plugins: refresh-packagekit, security
Setting up Install Process
No package node-pty available.
Error: Nothing to do
[root@xxb001 xterm.js]# proxychains4 npm install node-pty
[proxychains] config file found: /usr/local//etc/proxychains.conf
[proxychains] preloading /usr/local//lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Strict chain  ...  192.168.24.161:1080  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  192.168.24.161:1080  ...  registry.npmjs.org:443  ...  OKstallable status
[proxychains] DLL init: proxychains-ng 4.12all generateActionsToTake
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12

> node-pty@0.4.1 install /usr/mtx/xterm.js/node_modules/node-pty
> node scripts/install.js

[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
{ Error: Command failed: node-gyp rebuild
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
module.js:491
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.39-200.24.1.el6uek.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/mtx/xterm.js/node_modules/node-pty
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) killed: false, code: 1, signal: null, cmd: 'node-gyp rebuild' }


> node-pty@0.4.1 postinstall /usr/mtx/xterm.js/node_modules/node-pty
> node scripts/post-install.js

[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.
npm WARN request-promise-native@1.0.4 requires a peer of request@^2.34 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ node-pty@0.4.1
added 115 packages and updated 93 packages in 15.584s
```

**Comment by hktalent** [comment]
@Tyriar 
@parisk
```
# npm start

> xterm@2.9.1 prestart /usr/mtx/xterm.js
> npm run build


> xterm@2.9.1 build /usr/mtx/xterm.js
> gulp build

[11:52:06] Using gulpfile /usr/mtx/xterm.js/gulpfile.js
[11:52:06] Starting 'tsc'...
[11:52:11] Finished 'tsc' after 4.66 s
[11:52:11] Starting 'browserify'...
[11:52:11] Starting 'browserify-addons'...
[11:52:11] Finished 'browserify-addons' after 402 ms
[11:52:11] Starting 'sorcery-addons'...
[11:52:11] Finished 'sorcery-addons' after 7.1 ms
[11:52:11] Finished 'browserify' after 429 ms
[11:52:11] Starting 'sorcery'...
[11:52:11] Finished 'sorcery' after 132 ms
[11:52:11] Starting 'build'...
[11:52:11] Finished 'build' after 48 Œºs

> xterm@2.9.1 start /usr/mtx/xterm.js
> node demo/app

Cannot find module '../build/Release/pty.node'
module.js:491
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m57.node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/mtx/xterm.js/node_modules/node-pty/lib/pty.js:18:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@2.9.1 start: `node demo/app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@2.9.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-12T03_52_12_491Z-debug.log
```

**Comment by mofux** [comment]
Just to make sure, have you tried running `npm install` inside the `/usr/mtx/xterm.js` directory?

```bash
cd /usr/mtx/xterm.js
rm -rf node_modules
npm install
```

**Comment by Tyriar** [comment]
This is the reason you can't build:

```
{ Error: Command failed: node-gyp rebuild
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
module.js:491
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

node-pty is not able to install/compile as nan isn't getting installed. I have no idea what's happening tbh, it's likely a problem with your environment as no one else has seen this before.
